**NumPy UltraQuick Tutorial**

In [1]:
import numpy as np 


In [4]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [6]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [8]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[67 94 72 57 80 60]


In [9]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.86718478 0.22843436 0.78443315 0.2479016  0.06779028 0.94326764]


In [10]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.86718478 2.22843436 2.78443315 2.2479016  2.06779028 2.94326764]


In [11]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[201 282 216 171 240 180]


## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

In [12]:
feature = np.arange(6,21) # write your code here
print(feature)
label = (feature*3)+4    # write your code here
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2. 

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.

In [13]:
noise = (np.random.random([15]) * 4) - 2    # write your code here
print(noise)
label = label + noise   # write your code here
print(label)

[ 0.9274585  -0.59215928 -1.69478179 -1.22580208 -1.77752349  1.54246625
 -1.97111779 -0.75880778  1.14808543  0.35451435  0.17339105  1.29449079
 -0.01926697 -1.33546946  0.61483239]
[22.9274585  24.40784072 26.30521821 29.77419792 32.22247651 38.54246625
 38.02888221 42.24119222 47.14808543 49.35451435 52.17339105 56.29449079
 57.98073303 59.66453054 64.61483239]
